In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

df = pd.read_csv("class_ipl_22-26_dataset.csv")

In [3]:
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [5]:
df.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players'],
      dtype='object')

In [6]:
df['winner'].tail(74)

293    Royal Challengers Bengaluru
294                 Mumbai Indians
295               Rajasthan Royals
296                   Punjab Kings
297                 Delhi Capitals
                  ...
362                 Delhi Capitals
363    Royal Challengers Bengaluru
364               Rajasthan Royals
365                 Gujarat Titans
366    Royal Challengers Bengaluru
Name: winner, Length: 74, dtype: object

In [9]:
print("Missing Values : ",df['winner'].isnull().sum())
print("Unique Values : ", df['winner'].nunique())

Missing Values :  7
Unique Values :  11

In [10]:
df['winner'] = df['winner'].fillna('No Result')

df['winner'].isnull().sum()

np.int64(0)

In [13]:
le = LabelEncoder()

df['winner_encoded'] = le.fit_transform(df['winner'])

df[['winner', 'winner_encoded']].tail(74)

                          winner  winner_encoded
293  Royal Challengers Bengaluru              10
294               Mumbai Indians               5
295             Rajasthan Royals               8
296                 Punjab Kings               7
297               Delhi Capitals               1
..                           ...             ...
362               Delhi Capitals               1
363  Royal Challengers Bengaluru              10
364             Rajasthan Royals               8
365               Gujarat Titans               2
366  Royal Challengers Bengaluru              10

[74 rows x 2 columns]

In [ ]:
#Display Encoding Mapping

mapping = pd.DataFrame({
    'winner':le.classes_,
    'Encoded value' : range(len(le.classes_))
})