In [2]:
import pandas as pd
from sklearn.preprocessing import MaxAbsScaler

In [3]:
df = pd.read_csv('class_ipl_22-26_dataset.csv')
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [18]:
X = df[['team1_runs', 'team2_runs']]
X.head()

   team1_runs  team2_runs
0         131         133
1         177         179
2         205         208
3         158         161
4         210         149

In [19]:
scaler = MaxAbsScaler()

X_scaled = scaler.fit_transform(X)

X_scaled = pd.DataFrame(X_scaled, columns=['team1_runs','team2_runs'])
X_scaled.head()

   team1_runs  team2_runs
0    0.456446    0.501887
1    0.616725    0.675472
2    0.714286    0.784906
3    0.550523    0.607547
4    0.731707    0.562264

In [20]:
comparision = pd.DataFrame({
    'Original' : X['team1_runs'],
    'Max Absolute Scaled' : X_scaled['team1_runs']
})

comparision.tail(74)

     Original  Max Absolute Scaled
293       201             0.700348
294       220             0.766551
295       127             0.442509
296       162             0.564460
297       141             0.491289
..        ...                  ...
362       203             0.707317
363       254             0.885017
364       243             0.846690
365       214             0.745645
366       155             0.540070

[74 rows x 2 columns]

In [21]:
print("Original Data")
print(X.describe())

print("\nScaled Data")
print(X_scaled.describe())

Original Data
       team1_runs  team2_runs
count  367.000000  367.000000
mean   185.070845  169.250681
std     36.516265   38.827661
min     25.000000    0.000000
25%    161.500000  150.500000
50%    187.000000  171.000000
75%    209.000000  196.000000
max    287.000000  265.000000

Scaled Data
       team1_runs  team2_runs
count  367.000000  367.000000
mean     0.644846    0.638682
std      0.127234    0.146519
min      0.087108    0.000000
25%      0.562718    0.567925
50%      0.651568    0.645283
75%      0.728223    0.739623
max      1.000000    1.000000