In [3]:
import pandas as pd

df = pd.read_csv('class_ipl_22-26_dataset.csv')

In [4]:
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,5,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [5]:
X = df[['team1_runs']]
X.head()

   team1_runs
0         131
1         177
2         205
3         158
4         210

In [7]:
mean = X['team1_runs'].mean()
minimum = X['team1_runs'].min()
maximum = X['team1_runs'].max()

print("Mean : ", mean)
print("Minumum : ",minimum)
print("Maximum : ", maximum)

Mean :  185.0708446866485
Minumum :  25
Maximum :  287

In [12]:
X_mean = X.copy()

X_mean['team1_runs'] = (X_mean['team1_runs']-mean)/(maximum-minimum)

X_mean.head()

   team1_runs
0   -0.206377
1   -0.030805
2    0.076065
3   -0.103324
4    0.095149

In [13]:
comparision = pd.DataFrame({
    'Original' : X['team1_runs'],
    "Mean Normalized" : X_mean['team1_runs']
})

comparision.head()

   Original  Mean Normalized
0       131        -0.206377
1       177        -0.030805
2       205         0.076065
3       158        -0.103324
4       210         0.095149

In [14]:
print("original Data")
print(X.describe())

print("\n Mean Normalized Data")
print(X_mean.describe())

original Data
       team1_runs
count  367.000000
mean   185.070845
std     36.516265
min     25.000000
25%    161.500000
50%    187.000000
75%    209.000000
max    287.000000

 Mean Normalized Data
         team1_runs
count  3.670000e+02
mean  -4.598199e-17
std    1.393751e-01
min   -6.109574e-01
25%   -8.996506e-02
50%    7.363188e-03
75%    9.133265e-02
max    3.890426e-01