In [1]:
import pandas as pd
from sklearn.preprocessing import OrdinalEncoder

df = pd.read_csv('IPLPlayerStat.csv')
df.head()

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings
0,0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,142.86,15.82,8.89,22.22,15.00,8.0,0.0
1,1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,115.83,12.95,6.00,6.00,6.00,8.0,0.0
2,2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,57.14,0.00,6.28,22.27,21.27,2.0,0.0
3,3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,70.67,9.33,0.00,0.00,0.00,2.0,0.0
4,4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,125.00,10.00,8.00,28.80,21.60,0.0,0.0

In [5]:
def player_form(avg):
    if avg <=10:
        return "Poor"
    elif avg <=15:
        return "Average"
    elif avg <=20:
        return "Good"
    elif avg <= 25:
        return "Excellent"
    else :
        return "Outstanding"

df["Player_Form"] = df["batting_avg"].apply(player_form)

df[["player", "batting_avg", "Player_Form"]].head()

           player  batting_avg Player_Form
0  A Ashish Reddy        10.00        Poor
1        A Badoni        14.64     Average
2      A Chandila         0.33        Poor
3        A Chopra         8.83        Poor
4     A Choudhary         5.00        Poor

In [6]:
df

,Unnamed: 0,player,runs,boundaries,balls_faced,wickets,balls_bowled,runs_conceded,matches,batting_avg,batting_strike_rate,boundaries_percent,bowling_economy,bowling_avg,bowling_strike_rate,catches,stumpings,Player_Form
0,0,A Ashish Reddy,280,31,196,18.0,270.0,400.0,28,10.00,142.86,15.82,8.89,22.22,15.00,8.0,0.0,Poor
1,1,A Badoni,161,18,139,2.0,12.0,12.0,11,14.64,115.83,12.95,6.00,6.00,6.00,8.0,0.0,Average
2,2,A Chandila,4,0,7,11.0,234.0,245.0,12,0.33,57.14,0.00,6.28,22.27,21.27,2.0,0.0,Poor
3,3,A Chopra,53,7,75,0.0,0.0,0.0,6,8.83,70.67,9.33,0.00,0.00,0.00,2.0,0.0,Poor
4,4,A Choudhary,25,2,20,5.0,108.0,144.0,5,5.00,125.00,10.00,8.00,28.80,21.60,0.0,0.0,Poor
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
600,600,Yash Dayal,0,0,1,11.0,205.0,296.0,9,0.00,0.00,0.00,8.66,26.91,18.64,1.0,0.0,Poor
601,601,Yashpal Singh,47,5,67,0.0,0.0,0.0,4,11.75,70.15,7.46,0.00,0.00,0.00,3.0,0.0,Average
602,602,Younis Khan,3,0,7,0.0,0.0,0.0,1,3.00,42.86,0.00,0.00,0.00,0.00,1.0,0.0,Poor
603,603,Yuvraj Singh,2754,367,2207,36.0,882.0,1091.0,129,21.35,124.78,16.63,7.42,30.31,24.50,29.0,0.0,Excellent
604,604,Z Khan,117,13,141,102.0,2276.0,2860.0,99,1.18,82.98,9.22,7.54,28.04,22.31,20.0,0.0,Poor

In [8]:
df["Player_Form"].unique()

array(['Poor', 'Average', 'Excellent', 'Good', 'Outstanding'],
      dtype=object)

In [14]:
encoder = OrdinalEncoder(categories=[["Poor", "Average", "Excellent", "Good","Outstanding",]])

df["Player_Form_Encoded"] = encoder.fit_transform(df[["Player_Form"]]). astype(int)

df[["Player_Form", "Player_Form_Encoded"]].tail(30)

     Player_Form  Player_Form_Encoded
575         Poor                    0
576  Outstanding                    4
577         Poor                    0
578         Poor                    0
579         Poor                    0
580      Average                    1
581         Poor                    0
582         Poor                    0
583         Poor                    0
584         Good                    3
585         Poor                    0
586         Poor                    0
587    Excellent                    2
588         Poor                    0
589         Poor                    0
590         Poor                    0
591         Poor                    0
592      Average                    1
593         Poor                    0
594         Good                    3
595         Poor                    0
596    Excellent                    2
597    Excellent                    2
598         Poor                    0
599         Good                    3
600         Poor                    0
601      Average                    1
602         Poor                    0
603    Excellent                    2
604         Poor                    0