<a href="https://colab.research.google.com/github/Prajyot-Ghadi/Machine-Learning-by-C2W/blob/main/simple_knn_imputer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('class_ipl_22-26_dataset_with_nulls.csv')
df.head()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,win_by_wickets,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players
0,26-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,field,131,5.0,...,6,UT Yadav,M Nayyar,AK Chaudhary,Nitin Menon,VK Sharma,Chirra Ravikanthreddy,20,"RD Gaikwad, DP Conway, RV Uthappa, AT Rayudu, ...","AM Rahane, VR Iyer, N Rana, SS Iyer, SW Billin..."
1,27-03-2022,2022,Mumbai,"Brabourne Stadium, Mumbai",Mumbai Indians,Delhi Capitals,Delhi Capitals,field,177,NaN,...,4,Kuldeep Yadav,Prakash Bhatt,RJ Tucker,HAS Khalid,J Madanagopal,N Pandit,20,"RG Sharma, Ishan Kishan, Anmolpreet Singh, Til...","PP Shaw, TL Seifert, Mandeep Singh, RR Pant, L..."
2,27-03-2022,2022,Mumbai,"Dr DY Patil Sports Academy, Mumbai",Royal Challengers Bangalore,Punjab Kings,Punjab Kings,field,205,2.0,...,5,OF Smith,M Nayyar,Nitin Menon,YC Barde,AK Chaudhary,R Pandit,20,"F du Plessis, Anuj Rawat, V Kohli, KD Karthik,...","MA Agarwal, S Dhawan, PBB Rajapaksa, LS Living..."
3,28-03-2022,2022,Mumbai,"Wankhede Stadium, Mumbai",Lucknow Super Giants,Gujarat Titans,Gujarat Titans,field,158,6.0,...,5,Mohammed Shami,DS Manohar,PG Pathak,VK Sharma,RJ Tucker,GR Sadashiv Iyer,20,"KL Rahul, Q de Kock, E Lewis, MK Pandey, DJ Ho...","Shubman Gill, MS Wade, V Shankar, HH Pandya, D..."
4,29-03-2022,2022,Pune,"Maharashtra Cricket Association Stadium, Pune",Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,210,6.0,...,0,SV Samson,Shakti Singh,BNJ Oxenford,UV Gandhe,KN Ananthapadmanabhan,MV Saidharshan Kumar,20,"JC Buttler, YBK Jaiswal, SV Samson, D Padikkal...","KS Williamson, Abhishek Sharma, RA Tripathi, N..."

In [4]:
df['team1_wickets'].isnull().sum()

np.int64(12)

In [5]:
df['team1_wickets'].head(20)

0      5.0
1      NaN
2      2.0
3      6.0
4      6.0
5     10.0
6      7.0
7     10.0
8      6.0
9      8.0
10     8.0
11     7.0
12     3.0
13     4.0
14     3.0
15     9.0
16     6.0
17     NaN
18     6.0
19     5.0
Name: team1_wickets, dtype: float64

In [11]:
from sklearn.impute import KNNImputer

imputer = KNNImputer(n_neighbors=3, weights = 'distance')
df['team1_wickets'] = imputer.fit_transform(df[['team1_wickets']])

In [12]:
df['team1_wickets'].isnull().sum()

np.int64(0)

In [13]:
df['team1_wickets'].head(20)

0      5.000000
1      6.242254
2      2.000000
3      6.000000
4      6.000000
5     10.000000
6      7.000000
7     10.000000
8      6.000000
9      8.000000
10     8.000000
11     7.000000
12     3.000000
13     4.000000
14     3.000000
15     9.000000
16     6.000000
17     6.242254
18     6.000000
19     5.000000
Name: team1_wickets, dtype: float64